version: "3"
services:
  service_jekyll:
    build:
      context: .
      dockerfile: dockerfile
    container_name: local_jekyll
    volumes:
      - ..:/workspace:cached
      - ..:/usr/src/app
    command: /bin/sh -c "cd /workspace && bundle install && jekyll serve -s /usr/src/app --watch --verbose --trace --host 0.0.0.0"
    # command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "4000:4000"
