name: Build and deploy this site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: jeffreytse/jekyll-deploy-action@v0.5.1
        env:
          PAGES_REPO_NWO: ${{ github.repository }}
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_baseurl: ''
          pre_build_commands: pacman -S --noconfirm nodejs npm
          branch: 'site'
